def towerExists = true

pipeline {

  agent {
    dockerfile {
      dir pipeliles
      args '-u root'
    }
  }

  stages {

    stage ('Get latest code') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '${branch}']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: '${git_name}']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitcred', url: '${git_repo_url}']]])
      }
    }

    stage ('Verify .tower exists') {
      steps {
        script {
          towerExists = false
          catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
            sh "ls ${git_name}/.tower"
            towerExists = true
          }
        }
      }
    }

    stage ('Install correct ansible version') {
      steps {
        sh '''
          #!/bin/sh
          pip install ansible==${ansible_version}
        '''
      }
    }

    stage ('Display versions') {
      when { expression { towerExists }}
      steps {
        sh '''
          #!/bin/sh
          python -V
          ansible --version
          tower-cli --version
        '''
      }
    }

    stage ('Pull dependencies') {
      when { expression { towerExists }}
      steps {
        withCredentials([usernamePassword(credentialsId: 'jenkins_user_on_gitlab_username_token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_TOKEN')]) {
          sh '''
            #!/bin/sh
            sed -i "s/USER/${GIT_USERNAME}/g" roles/requirements.yml
            sed -i "s/TOKEN/${GIT_TOKEN}/g" roles/requirements.yml
            ansible-galaxy install -f -r roles/requirements.yml
          '''
        }
      }
    }

    stage ('Throw at Tower') {
      when { expression { towerExists }}
      steps {
        withCredentials([string(credentialsId: 'ansible-vault', variable: 'VAULTPASS')]) {
          sh '''
            touch /tmp/vaultpass
            echo ${VAULTPASS} > /tmp/vaultpass
          '''
        }
        sh '''
          #!/bin/sh
          ansible-playbook playbooks/automate_tower.yml -e vars/tower.yml -e @${git_name}/.tower/tower_vars.yml -e var_location="../${git_name}/.tower" -e tower_manage_proj_branch=${branch} -i inventory/hosts-${target} --vault-password-file=/tmp/vaultpass
          rm /tmp/vaultpass
        '''
      }
    }

  }
}