---
# Playbook to seed Ansible Tower
- name: Install Tower to VM
  hosts: tower
  vars_files:
    - "../vars/seed.yml"
  tasks:
    - name: Create Virtualenv
      become: true
      pip:
        virtualenv: "/var/lib/awx/venv/{{ item.name }}"
        name: "{{ item.packages }}"
      with_items: "{{ virtualenvs }}"

    - include_role:
        name: ansible-tower-manage
        tasks_from: "{{ tower_tasks }}.yml"
      loop:      # Include  specific task file
        - tower_orgs
        - tower_credential
        - tower_project
        - tower_inventories
        - tower_inventory_source
        - tower_job
      loop_control:
        loop_var: tower_tasks
      vars:
        tower_manage_server: "https://{{ inventory_hostname }}"
        tower_manage_validate_certs: false
